-- MySQL Script generated by MySQL Workbench
-- Wed Jun 16 16:37:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`addresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`addresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresse_ligne_1` VARCHAR(155) NULL DEFAULT NULL,
  `adresse_ligne_2` VARCHAR(45) NULL DEFAULT NULL,
  `ville` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `code_postale` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `adresse_email` VARCHAR(45) NULL DEFAULT NULL,
  `addresse_id` INT NOT NULL,
  PRIMARY KEY (`id`, `addresse_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_client_addresse1_idx` (`addresse_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_addresse1`
    FOREIGN KEY (`addresse_id`)
    REFERENCES `mydb`.`addresse` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizzeria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `num_telephone` VARCHAR(45) NULL DEFAULT NULL,
  `addresse_id` INT NOT NULL,
  PRIMARY KEY (`id`, `addresse_id`),
  INDEX `fk_pizzeria_addresse1_idx` (`addresse_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizzeria_addresse1`
    FOREIGN KEY (`addresse_id`)
    REFERENCES `mydb`.`addresse` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_reception` VARCHAR(70) NULL DEFAULT NULL,
  `statut` VARCHAR(70) NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  `client_id` INT NOT NULL,
  `pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `pizzeria_id`),
  UNIQUE INDEX `idcommande_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_commande_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_commande_pizzeria1_idx` (`pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`),
  CONSTRAINT `fk_commande_pizzeria1`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `mydb`.`pizzeria` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `employe_nom` VARCHAR(45) NOT NULL,
  `employee_prenom` VARCHAR(45) NOT NULL,
  `employee_fonction` VARCHAR(45) NOT NULL,
  `pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`idemployee`, `pizzeria_id`),
  INDEX `fk_employee_pizzeria1_idx` (`pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_pizzeria1`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `mydb`.`pizzeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `taille` VARCHAR(45) NULL DEFAULT NULL,
  `prix_unitaire_ht` FLOAT NULL DEFAULT NULL,
  `taux_tva_100` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recette` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `etapes` VARCHAR(400) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recette_pizza_idx` (`pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_recette_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients_recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredients_recette` (
  `ingredients_id` INT NOT NULL,
  `recette_id` INT NOT NULL,
  `quantite` FLOAT NULL DEFAULT NULL,
  `unite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ingredients_id`, `recette_id`),
  INDEX `fk_ingredients_has_recette_recette1_idx` (`recette_id` ASC) VISIBLE,
  INDEX `fk_ingredients_has_recette_ingredients1_idx` (`ingredients_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredients_has_recette_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`ingredients` (`id`),
  CONSTRAINT `fk_ingredients_has_recette_recette1`
    FOREIGN KEY (`recette_id`)
    REFERENCES `mydb`.`recette` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ligne_commande` (
  `commande_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `quantite` VARCHAR(45) NULL DEFAULT NULL,
  `prix_unitaire` FLOAT NULL DEFAULT NULL,
  `taux_tva_100` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`commande_id`, `pizza_id`),
  INDEX `fk_commande_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_commande_has_pizza_commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_has_pizza_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`),
  CONSTRAINT `fk_commande_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`stock_ingredients_pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_ingredients_pizzeria` (
  `pizzeria_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  `quantite_ingrdients` FLOAT NULL DEFAULT NULL,
  `unite_ingredients` FLOAT NULL DEFAULT NULL,
  `quantite_minimal` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pizzeria_id`),
  INDEX `fk_stock_ingredients_pizzeria_ingredients1_idx` (`ingredients_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_ingredients_pizzeria_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`ingredients` (`id`),
  CONSTRAINT `fk_stock_ingredients_pizzeria_pizzeria1`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `mydb`.`pizzeria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
